### ISSUE TITLE
Stable for use?

### ISSUE THREAD

**Issue by ivanjeremic** [GiovanniCardamone/fastify-autoroutes#108]
Hello is this lib stable and maintained?

**Comment by GiovanniCardamone** [comment]
i use it in 2 different project in production.

Internally it uses fastify binding, the only relevant part is the recursive strategy to find and build route, and is pretty simple, is actually just one file.

In some time i plan to add also more-strict type checking for the schema of the body, parameters and query to have more feedback by typescript.

**Comment by ivanjeremic** [comment]
> i use it in 2 different project in production.
> 
> Internally it uses fastify binding, the only relevant part is the recursive strategy to find and build route, and is pretty simple, is actually just one file.
> 
> In some time i plan to add also more-strict type checking for the schema of the body, parameters and query to have more feedback by typescript.

Thanks just found "fastify-autoload" which is a core plugin and also implements file-system-based routing.
