### ISSUE TITLE
Support for generics for types in methods.

### ISSUE THREAD

**Issue by karmabadger** [GiovanniCardamone/fastify-autoroutes#187]
### Feature description

Support for generics for types in methods.
Something similar to what fastify already has for their method routes. 
for instances: 
```ts
server.get<{
    Querystring: IQuerystring;
    Headers: IHeaders;
    Reply: ReplyBodyType;
  }>(fullpath, async (request, reply) => {
    console.log("name");
    reply.status(200).send({ success: true, message: "hello world" });
  });
```
This types all of the querystring, headers, and reply using a very nice and simple and neat syntax.

### Feature motivation

Typing is quite neat and useful in TS. And this way and syntax is also very nice. 
Thanks

**Comment by GiovanniCardamone** [comment]
you can already do this, here an example:

```
import { enums, use } from 'class-schema'

interface RequestIndex extends RequestGenericInterface {}

interface GetRequestIndex extends RequestIndex {}

@schema()
export class ServerStatus {
  @enums(['running', 'manteniance'])
  status!: string
}


export default (fastify: FastifyInstance): StrictResource => ({
  get: {
    schema: {
      summary: 'get server status',
      description: 'get informations about server',
      tags: ['Server'],
      consumes: ['application/json'],
      produces: ['application/json'],
      response: {
        200: use(ServerStatus),
      },
    },
    handler: async (
      request: FastifyRequest<GetRequestIndex>
    ): Promise<ServerStatus> => ({
      status: 'running',
    }),
  },
})

```

**Comment by karmabadger** [comment]
oh this is very neat, does this deal with run time type checking as well?

**Comment by GiovanniCardamone** [comment]
No, types annotation does not deal with types at runtime. For that there is fastify that does that (ajv usually for request types)

As you can see, there is types declaration in "schema" that deals with that, and types annotation (wich reflect types annotation) in handler

**Comment by irg1008** [comment]
I think this brings as much boilerplate to the route declaration as actually registering routes. Can we have another solution or maybe allow plugin-based route declaration?

**Comment by GiovanniCardamone** [comment]
not sure what you mean, can you explain what you want to accomplish?

**Comment by irg1008** [comment]
I mean, are we able to export routes as we do with fastify, exporting an AsyncPlugin

**Comment by GiovanniCardamone** [comment]
I think the original question made from @karmabadger was to enable the `StrictResource` type to allow Generics to define each route.

something like this actually

```typescript
export default (server): StrictResource<GetReuqest, PostRequest, ...> => ({
  get: ... // here types are inferred from GetRequest
  post: ... // here types are inferred from PostReqiest
})
```

you can use the route without using the typescript as well, like:

```typescript
export default (server) => ({
  get: ... // here you deal with the types
  post: ... // here you deal with the types
})
```

it's not related to how you do import/export. 

I could create a builder that just annotate the thing is a strict resource and gives you fastify, like:

```typescript
export default wrapper<GenericThatDescribeGetPostAndEtc>((server /* server and expected return are inferred */) => ({
    get: ... // here types are inferred from GenericThatDescribeGetPostAndEtc['get'],
    post: ...// here types are inferred from GenericThatDescribeGetPostAndEtc['post']
}))
```

but this won't solve boilerplate code. Not sure if the solution above it's really performant but it's doable
