### ISSUE TITLE
Support for Fastify 4.0

### ISSUE THREAD

**Issue by damey2011** [GiovanniCardamone/fastify-autoroutes#191]
Currently, you cannot install along Fastify 4.0, dependency resolution fails. Can we have support for Fastify 4.0?

**Comment by GiovanniCardamone** [comment]
I'll look in this week what's new in  fastify 4.0, and how to support it.

Thanks for reporting

**Comment by Raiden-Ei** [comment]
Any updates on this?

**Comment by GiovanniCardamone** [comment]
done in https://github.com/GiovanniCardamone/fastify-autoroutes/pull/194
