### ISSUE TITLE
Is there a reason why @fastify/error is listed as DevDependency ?

### ISSUE THREAD

**Issue by mgara** [GiovanniCardamone/fastify-autoroutes#195]

**Comment by GiovanniCardamone** [comment]
yes, the reason is i messed it up: https://github.com/GiovanniCardamone/fastify-autoroutes/pull/193#issuecomment-1288084160

Thankyou for reporting I'll fix this

**Comment by GiovanniCardamone** [comment]
fixed in v3.0.1
