### ISSUE TITLE
Route conversion

### ISSUE THREAD

**Issue by devtatsuki** [GiovanniCardamone/fastify-autoroutes#198]
Hello! Sorry about my english.

Basically, if i create a route folder and a index, when i remove the last slash of url, route is not found.
Looks like its enter in other route without a sub route.

Example:

**routes/users/index.ts**
http://localhost:3333/users --- doesn't work
http://localhost:3333/users/ --- works

**routes/users.ts**
http://localhost:3333/users --- works
http://localhost:3333/users/ --- doesn't work

I think its better if works with and without slash at the end of url.

**Comment by GiovanniCardamone** [comment]
Hello @devtatsuki.

this is controllable by fastify option `ignoreTrailingSlash` https://www.fastify.io/docs/latest/Reference/Server/#ignoretrailingslash

not part of route loading.

if you want to have this behaivour just set this option to true in your server initialization.
