### ISSUE TITLE
Add "Prefix" feature.

### ISSUE THREAD

**Issue by ashermyers** [GiovanniCardamone/fastify-autoroutes#199]
### Feature description

"Prefix" feature, allow a base such as "/api" without nesting all routes in the /routes/api folder

### Feature motivation

ease of use, similar to nextjs.

Implementation:

```
app.register(fastifyAutoRoutes, {
    dir: path.join(staticPath, 'routes'),
    ignorePattern: /.*\.test\.js/,
    prefix: "/api/"
});
```

**Comment by GiovanniCardamone** [comment]
this feature already exists and works as you described, maybe isn't documented in the docs, i have to check

**Comment by GiovanniCardamone** [comment]
added in the readme [559d27f](https://github.com/GiovanniCardamone/fastify-autoroutes/commit/559d27ff2400734d09dd4976e2161380f5dfa900)
