### ISSUE TITLE
subroute multiple keys

### ISSUE THREAD

**Issue by rubybb** [GiovanniCardamone/fastify-autoroutes#49]
### Feature description

Route directories when they contain a :key path ignore all others in the directory.
I'm hoping for support for something like this, this is just an example.
```
/users/
/users/{uuid}/
/users/create/
```
`users/create` isn't available because it'd be passed to `users/{uuid}`.
### Feature motivation

More complex and detailed API structures.

**Comment by GiovanniCardamone** [comment]
You can achieve this using wildcards, also because "create" can be a valid uuid in this example.

for example i will use a pattern like this:

```text
/users/
/users/@{uuid}/
/users/create/
```

you can replace the `@` with any "special" character you want
